# cluster-install.yaml
---
  - hosts: master
    gather_facts: no
    tasks:

      - name: Reset previous Kubernetes control plane if any
        become: true
        shell: kubeadm reset -f

      - name: Cleanup credentials
        become: true
        shell: rm -f /etc/kubernetes/admin.conf

      - name: Install Kube master
        become: true
        shell: kubeadm init --pod-network-cidr 192.168.0.0/16 --kubernetes-version 1.24.0

      - name: Configure kube master - 3
        become: true
        shell: chown $(id -u):$(id -g) /etc/kubernetes/admin.conf

      - name: Retry till controller manager is healthy
        become: true
        ansible.builtin.shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf get cs | grep controller-manager
        register: result
        until: result.stdout.find("Healthy") != -1
        retries: 30
        delay: 10

      - name: Retry till scheduler is healthy
        become: true
        ansible.builtin.shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf get cs | grep scheduler
        register: result
        until: result.stdout.find("Healthy") != -1
        retries: 30
        delay: 10

      - name: Install CNI
        become: true
        shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/manifests/calico.yaml

      - name: Get Join Command
        become: true
        shell:  kubeadm token create --print-join-command
        register: k8s_join_command

      - debug:
          var: k8s_join_command

  - hosts: nodes
    gather_facts: no
    tasks:
      - name: Reset previous Kubernetes control plane if any
        become: true
        shell: kubeadm reset -f

      - name: Cleanup credentials
        become: true
        shell: rm -f /etc/kubernetes/admin.conf

      - name: Join master
        become: true
        shell: "{{ hostvars['master']['k8s_join_command'].stdout }}"
        when: hostvars['master']['k8s_join_command'] is defined

