# configure-system.yaml
---
  - hosts: master:nodes
    tasks:

      - name: Configure overlay for containerd
        become: true
        ansible.builtin.lineinfile: path=/etc/modules-load.d/containerd.conf regexp='overlay$' line='overlay' create=true

      - name: Configure br_netfilter for containerd
        become: true
        ansible.builtin.lineinfile: path=/etc/modules-load.d/containerd.conf regexp='br_netfilter$' line='br_netfilter' create=true

      - name: Enable overlay module
        become: true
        shell: modprobe overlay

      - name: Enable br_netfilter module
        become: true
        shell: modprobe br_netfilter

      - name: Configure iptables
        become: true
        ansible.builtin.lineinfile: path=/etc/sysctl.d/99-kubernetes-cri.conf regexp='^net.bridge.bridge-nf-call-iptables' line='net.bridge.bridge-nf-call-iptables=1' create=true

      - name: Configure iptables6
        become: true
        ansible.builtin.lineinfile: path=/etc/sysctl.d/99-kubernetes-cri.conf regexp='^net.bridge.bridge-nf-call-ip6tables' line='net.bridge.bridge-nf-call-ip6tables=1' create=true

      - name: Configure ip_forward
        become: true
        ansible.builtin.lineinfile: path=/etc/sysctl.d/99-kubernetes-cri.conf regexp='^net.ipv4.ip_forward' line='net.ipv4.ip_forward=1' create=true

      - name: Enable br_netfilter module
        become: true
        shell: sysctl --system

      - name: Update apt-get repo and cache
        become: true
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

      - name: Install containerd
        become: true
        ansible.builtin.apt:
          pkg:
          - containerd

      - name: Create containerd directory
        become: true
        shell: mkdir -p /etc/containerd

      - name: Configure containerd
        become: true
        shell: containerd config default | tee /etc/containerd/config.toml

      - name: Restart containerd
        become: true
        shell: systemctl restart containerd

      - name: Disable Swap
        become: true
        shell: swapoff -a

      - name: Update apt-get repo and cache
        become: true
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

      - name: Install apt-transport-https and curl
        become: true
        ansible.builtin.apt:
          pkg:
            - apt-transport-https
            - curl